# Generated by Django 3.1.2 on 2020-10-05 17:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='IssueBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, default=inventory.models.issue_bill_number, max_length=500, null=True, unique=True)),
                ('issued_by', models.CharField(max_length=50)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('decs', models.CharField(max_length=250)),
                ('current_stock', models.PositiveIntegerField(blank=True, default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(default=0.0)),
                ('stock', models.PositiveIntegerField(blank=True, default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_detail', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, default=inventory.models.purchase_bill_number, max_length=500, null=True, unique=True)),
                ('supplier', models.CharField(max_length=50)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.unitgroup')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='inventory.category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('mrp_per_unit', models.IntegerField(default=0)),
                ('bill_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='inventory.purchasebill')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemdetails')),
            ],
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='unit_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unitgroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='inventory.subcategory'),
        ),
        migrations.CreateModel(
            name='IssueOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bill_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_items', to='inventory.issuebill')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.itemdetails')),
            ],
        ),
    ]
