# Generated by Django 3.1.2 on 2020-10-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='mrp_per_unit',
            field=models.IntegerField(),
        ),
    ]
