# Generated by Django 3.1.2 on 2020-10-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201012_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebill',
            name='supplier',
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
