# Generated by Django 2.2.15 on 2020-10-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20201014_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='category',
            new_name='item',
        ),
    ]
